[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.134.2"
HUGO_EXTENDED = "true"
HUGO_ENV = "production"
# Jeśli używasz Hugo Modules:
# GO_VERSION = "1.22.0"
